#!/bin/sh

# set-aliases
#
# Copyright (c) 2014, Andrew Keller
#
# Adds all of the git aliases I like to have.

# Displays a commit graph:
git config --global alias.graph 'log --graph --oneline --decorate'

# Runs `git clean` with the given arguments in the top-level of the superproject
# and all submodules:
git config --global alias.scrub 'tenv --recursive git clean'

# A wrapper around `git repocache-submodule` that runs at the top-level of the
# current repository, and passes additional arguments:
git config --global alias.su 'env git repocache-submodule update --recursive'

echo "All Git aliases set." >&2
